---
galaxy_info:
  author: "Maor Lipchuk"
  description: "Disaster recovery for oVirt engine"
  company: Red Hat, Inc.
  license: Apache License 2.0
  min_ansible_version: 2.7.2
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
      - all
  galaxy_tags: [ovirt, rhv, rhev, virtualization]
