---
galaxy_info:
  author: Simone Tiraboschi
  description: Role to shutdown cleanly all the entities in a oVirt/RHV environment.
  company: Red Hat, Inc.
  role_name: shutdown_env

  license: Apache License 2.0

  min_ansible_version: 2.7

  platforms:
  - name: EL
    versions:
      - all
  - name: Fedora
    versions:
      - all

  galaxy_tags: [ovirt, rhv, rhev, virtualization]

dependencies: []
