---
- include_tasks: "install-manageiq-build-conversion-host-resource-{{ v2v_host_type }}.yml"

- uri:
    url: "{{ manageiq_url }}/api/conversion_hosts"
    user: "{{ manageiq_username }}"
    password: "{{ manageiq_password }}"
    method: "POST"
    validate_certs: "{{ manageiq_validate_certs | default(true) }}"
    body_format: "json"
    body:
      action: "create"
      resource: "{{ manageiq_post_conversion_host_resource }}"
  when:
    - "manageiq_post_conversion_host_resource is defined"

- block:
    - set_fact:
        manageiq_conversion_host_resource_tags:
          - category: "v2v_transformation_host"
            name: "true"

    - set_fact:
        manageiq_tag_vddk_transport:
          - category: "v2v_transformation_method"
            name: "vddk"

    - set_fact:
        manageiq_tag_ssh_transport:
          - category: "v2v_transformation_method"
            name: "ssh"

    - set_fact:
        manageiq_conversion_host_resource_tags: "{{ manageiq_conversion_host_resource_tags }} + {{ manageiq_tag_vddk_transport }}"
        when:
          - "'vddk' in v2v_transport_methods"

    - set_fact:
        manageiq_conversion_host_resource_tags: "{{ manageiq_conversion_host_resource_tags }} + {{ manageiq_tag_ssh_transport }}"
        when:
          - "'ssh' in v2v_transport_methods"

    - name: Tag as conversion host
      uri:
        url: "{{ manageiq_post_conversion_host_resource_href }}/tags"
        user: "{{ manageiq_username }}"
        password: "{{ manageiq_password }}"
        method: "POST"
        validate_certs: "{{ manageiq_validate_certs | default(true) }}"
        body_format: "json"
        body:
          action: "assign"
          resources: "{{ manageiq_conversion_host_resource_tags }}"

  when:
    - "manageiq_post_conversion_host_resource_href is defined"
