- block:
    - name: Fetch unregistered Templates from storage domain
      ovirt_storage_template_facts:
          nested_attributes: "id"
          unregistered: True
          storage_domain: "{{ storage.name }}"
          auth: "{{ ovirt_auth }}"

    - name: Register template
      include: tasks/recover/register_template.yml
      # The main task already declared ignore errors so that might bredundant to put it here
      # ignore_errors: "{{ ignore | default(yes) }}"
      with_items: "{{ ovirt_storage_templates }}"
      # We use loop_control so storage.name will not be overriden by the nested loop.
      loop_control:
          loop_var: unreg_template
  ignore_errors: "{{ dr_ignore_error_recover }}"
  tags:
      - fail_over
      - fail_back
